import fundingImage from "../img/fundingImage.png";

const initialState = [
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
  {
    title: "칫솔모 교체가 정말 쉬운 친환경 펀딩",
    number: 358,
    user: "abc@gmail.com",
    image: fundingImage,
    id: "a9393bcef03",
  },
];

const fundingReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

export default fundingReducer;
